fix: upgraded management sdk to 1.11.0
contentstack/cli pull request #1120
Opened 2023-10-23 08:43 UTC by vkalta

2023-10-25 10:18 UTC, netrajpatel requested changes

2023-10-25 10:18 UTC, netrajpatel commented on packages/contentstack-import/package.json
>    "dependencies": {
@vkalta Can you please bump the package version?

2023-10-25 10:18 UTC, netrajpatel commented on packages/contentstack-utilities/package.json
>    "author": "contentstack",
@vkalta Can you please bump the package version?

2023-10-25 10:18 UTC, netrajpatel commented on packages/contentstack/package.json
>      "@contentstack/cli-launch": "~1.0.13",
@vkalta Can you please bump the package version?

2023-10-25 10:19 UTC, netrajpatel commented
@vkalta Can you please update the description of this PR ?

2023-10-26 10:15 UTC, netrajpatel submitted a review, later dismissed

2023-10-26 10:15 UTC, netrajpatel approved these changes

2023-11-03 08:16 UTC, antonyagustine approved these changes

2023-11-03 08:25 UTC, netrajpatel approved these changes

2023-11-03 08:39 UTC, merged