added external config
contentstack/cli pull request #1259
Opened 2024-01-24 10:02 UTC by shafeeqd959

2024-01-24 11:29 UTC, antonyagustine commented
@shafeeqd959 Please resolve the conflict.

2024-01-24 11:54 UTC, netrajpatel approved these changes

2024-01-24 11:54 UTC, netrajpatel requested changes
@shafeeqd959 Please resolve the conflicts

2024-01-24 11:57 UTC, netrajpatel submitted a review, later dismissed

2024-01-24 13:28 UTC, cs-raj submitted a review, later dismissed

2024-01-25 05:07 UTC, antonyagustine approved these changes

2024-01-25 05:12 UTC, aman19K approved these changes

2024-01-25 09:35 UTC, merged