Config handler fixes
contentstack/cli pull request #304
Opened 2022-06-06 14:23 UTC by antonyagustine

- Lodash dependency dependency added in package manager

2022-06-06 14:34 UTC, netrajpatel reviewed
@antonyagustine Though the complexity wise both ways looks simillar, using lodash.isEmpty() makes our code more readable as well as handles more cases of array as well as object with boolean return type rather than integer.
Also, we should use uniform code structure everywhere to reduce the further confusions, So I think, you should use the lodash isEmpty which is better maintainable in future as well.
I'm open for any further discussions, let me know.

2022-06-07 05:04 UTC, antonyagustine commented
> @antonyagustine Though the complexity wise both ways looks simillar, using lodash.isEmpty() makes our code more readable as well as handles more cases of array as well as object with boolean return type rather than integer. Also, we should use uniform code structure everywhere to reduce the further confusions, So I think, you should use the lodash isEmpty which is better maintainable in future as well. I'm open for any further discussions, let me know.

@netrajpatel I've reverted the code back to lodash. @shafeeqd959 As we discussed I've added lodash dependency in package manager.

2022-06-08 06:35 UTC, netrajpatel requested changes

2022-06-08 06:35 UTC, netrajpatel commented on packages/contentstack-utilities/src/logger.ts
> +// import config from './config-handler';
Remove unused/commented code

2022-06-08 07:23 UTC, merged