fix(export-to-csv): fixed pagination issue with entires
contentstack/cli pull request #306
Opened 2022-06-07 06:30 UTC by vkalta

2022-06-07 06:31 UTC, netrajpatel requested changes
@vkalta Please update the package versions as well.

2022-06-07 08:25 UTC, netrajpatel requested changes
@vkalta The package versions are still not updated in all dependant package and package-lock json files - 
below are the files which are still showing old versions - 
packages/contentstack/package.json
packages/contentstack-export-to-csv/package-lock.json

2022-06-07 17:00 UTC, vkalta commented
@netrajpatel Updated the versions.

2022-06-08 05:38 UTC, netrajpatel approved these changes

2022-06-08 07:27 UTC, merged