skipped validate api key check to support adding mgmt tokens
contentstack/cli pull request #469
Opened 2022-08-30 15:47 UTC by vkalta

This PR resolves CS-29665 and CS-29967.

2022-09-07 06:40 UTC, netrajpatel requested changes

2022-09-07 11:39 UTC, shafeeqd959 commented
@vkalta, user should be able add management token without login into the CLI. Please logout before testing these changes. Here management client is being initiated using "this.authtoken" that will throw an error in case of logged out user. We have to initiate management API client using management token, then stack using API key. For more clarification, we can connect. Ping me on slack

CC: @netrajpatel

2022-09-07 11:45 UTC, shafeeqd959 commented
@vkalta , Please connect with on this, before proceeding it further

CC: @netrajpatel

2022-09-08 14:53 UTC, vkalta commented
@shafeeqd959 @netrajpatel All the changes requested are added and custom region issue is also fixed.

2022-09-13 11:23 UTC, merged