added changeMasterLocale
contentstack/cli pull request #503
Opened 2022-10-11 06:26 UTC by abhinav-from-contentstack

2022-10-11 07:54 UTC, netrajpatel commented
@abhinav-from-contentstack Replace the camel-case folder name and use `-` rather.
we have followed similar folder structure in CLI

packages/contentstack-migration/examples/**changeMasterLocale**/01-change-master-locale.js

2022-10-11 08:33 UTC, netrajpatel requested changes
@abhinav-from-contentstack Replace the camel-case folder name(changeMasterLocale) and use `-` rather.
we have followed similar folder structure in CLI

packages/contentstack-migration/examples/**changeMasterLocale**/01-change-master-locale.js

2022-10-11 11:35 UTC, netrajpatel approved these changes

2022-10-12 07:06 UTC, abhinav-from-contentstack commented
> @abhinav-from-contentstack , please prepare a doc to explain the steps to execute the script.

Hi Shafeeq, I'll be updating the current doc that we have as soon as the docs team shares it with us for technical review.

2022-10-12 10:13 UTC, shafeeqd959 approved these changes

2022-10-13 05:55 UTC, merged