OAuth Redirect url issue fixed
contentstack/cli pull request #615
Opened 2023-02-03 08:54 UTC by antonyagustine

**Tickets: CS-32684, CS-34614**
- Code clean
- MKT apps OAuth Redirect URL issue fix
- HTTP client type definition correction, new constructor params introduced.

2023-02-06 15:31 UTC, netrajpatel requested changes

2023-02-06 15:31 UTC, netrajpatel commented on packages/contentstack-import/src/lib/import/marketplace-apps.js
> +        log(this.config, formatError(error), 'succeiiss');
Is this a typo?

2023-02-07 05:22 UTC, antonyagustine commented on packages/contentstack-import/src/lib/import/marketplace-apps.js
> +        log(this.config, formatError(error), 'succeiiss');
Yes, it was a typo, Fixed it.

2023-02-07 05:41 UTC, netrajpatel approved these changes

2023-02-07 05:50 UTC, merged